### PR TITLE
Script to migrate data from DB to ES

### LINKED ISSUE #62: Script to update ES with data from DB
Create a script that can be run through npm.

The script takes all data present in DynamoDB and upserts (insert if does not exist, update if otherwise) data in Elasticsearch.

You can assume that the script will be run during downtime / maintenance only, so you need not worry about new records or updates happening to the data in the DB while the script is running.

### PR DESCRIPTION
**Pull request by sharathkumaranbu**
Fixes #62

### CODE REVIEW

**Comment by sharathkumaranbu** [comment]
@callmekatootie FYA

**Comment by callmekatootie** [comment]
Changes look fine. Tested as well. However, a code recommendation - you could write just one generic function to which you pass the resource name instead of writing four functions that look almost alike.

**Comment by sharathkumaranbu** [comment]
@callmekatootie I have modified the code to follow DRY principle. I usually follow DRY principle but I am not sure how I missed in this ticket. Sorry about that.

**Comment by callmekatootie** [comment]
Thanks! This looks good to merge @BadalZ

**Pull request merged**
